AWSTemplateFormatVersion: "2010-09-09"
Mappings:
  CertbotLayer:
    ap-east-1:
      python36: "arn:aws:lambda:ap-east-1:966028770618:layer:certbot-py36:2"
      python37: "arn:aws:lambda:ap-east-1:966028770618:layer:certbot-py37:2"
      python38: "arn:aws:lambda:ap-east-1:966028770618:layer:certbot-py38:1"
    ap-northeast-1:
      python36: "arn:aws:lambda:ap-northeast-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:ap-northeast-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:ap-northeast-1:966028770618:layer:certbot-py38:1"
    ap-northeast-2:
      python36: "arn:aws:lambda:ap-northeast-2:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:ap-northeast-2:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:ap-northeast-2:966028770618:layer:certbot-py38:1"
    ap-south-1:
      python36: "arn:aws:lambda:ap-south-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:ap-south-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:ap-south-1:966028770618:layer:certbot-py38:1"
    ap-southeast-1:
      python36: "arn:aws:lambda:ap-southeast-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:ap-southeast-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:ap-southeast-1:966028770618:layer:certbot-py38:1"
    ap-southeast-2:
      python36: "arn:aws:lambda:ap-southeast-2:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:ap-southeast-2:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:ap-southeast-2:966028770618:layer:certbot-py38:1"
    ca-central-1:
      python36: "arn:aws:lambda:ca-central-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:ca-central-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:ca-central-1:966028770618:layer:certbot-py38:1"
    eu-central-1:
      python36: "arn:aws:lambda:eu-central-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:eu-central-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:eu-central-1:966028770618:layer:certbot-py38:1"
    eu-north-1:
      python36: "arn:aws:lambda:eu-north-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:eu-north-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:eu-north-1:966028770618:layer:certbot-py38:1"
    eu-west-1:
      python36: "arn:aws:lambda:eu-west-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:eu-west-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:eu-west-1:966028770618:layer:certbot-py38:1"
    eu-west-2:
      python36: "arn:aws:lambda:eu-west-2:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:eu-west-2:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:eu-west-2:966028770618:layer:certbot-py38:1"
    eu-west-3:
      python36: "arn:aws:lambda:eu-west-3:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:eu-west-3:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:eu-west-3:966028770618:layer:certbot-py38:1"
    me-south-1:
      python36: "arn:aws:lambda:me-south-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:me-south-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:me-south-1:966028770618:layer:certbot-py38:1"
    sa-east-1:
      python36: "arn:aws:lambda:sa-east-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:sa-east-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:sa-east-1:966028770618:layer:certbot-py38:1"
    us-east-1:
      python36: "arn:aws:lambda:us-east-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:us-east-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:us-east-1:966028770618:layer:certbot-py38:1"
    us-east-2:
      python36: "arn:aws:lambda:us-east-2:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:us-east-2:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:us-east-2:966028770618:layer:certbot-py38:1"
    us-west-1:
      python36: "arn:aws:lambda:us-west-1:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:us-west-1:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:us-west-1:966028770618:layer:certbot-py38:1"
    us-west-2:
      python36: "arn:aws:lambda:us-west-2:966028770618:layer:certbot-py36:1"
      python37: "arn:aws:lambda:us-west-2:966028770618:layer:certbot-py37:1"
      python38: "arn:aws:lambda:us-west-2:966028770618:layer:certbot-py38:1"
    us-gov-east-1:
      python36: "arn:aws-us-gov:lambda:us-gov-east-1:678832456889:layer:certbot-py36:1"
      python37: "arn:aws-us-gov:lambda:us-gov-east-1:678832456889:layer:certbot-py37:1"
      python38: "arn:aws-us-gov:lambda:us-gov-east-1:678832456889:layer:certbot-py38:1"
    us-gov-west-1:
      python36: "arn:aws-us-gov:lambda:us-gov-west-1:678832456889:layer:certbot-py36:1"
      python37: "arn:aws-us-gov:lambda:us-gov-west-1:678832456889:layer:certbot-py37:1"
      python38: "arn:aws-us-gov:lambda:us-gov-west-1:678832456889:layer:certbot-py38:1"
  CertbotToACMFunctionZIP:
    ap-east-1:
      version: "MZsbCcXEZmeKc_UDrr56iHYAt.q.FNoY"
    ap-northeast-1:
      version: "KUVpb3z4p685NogqGshYVgnAsrBSwCSY"
    ap-northeast-2:
      version: "e6CEwA19.Gmqcf.iEbqv0zdR3JpfkLHx"
    ap-south-1:
      version: "s6xVpxHFK_.rqQgVGXQm4GSz9qT0xvvf"
    ap-southeast-1:
      version: "XMf_z7c4enAfURuYfw9I5idRVwQaW5HS"
    ap-southeast-2:
      version: "ogiSf1fFMdY4a4x23Y.XOwDOjlROnp7W"
    ca-central-1:
      version: "r3_2WcyZReJZDNzR5KyRHrGvoL98.kZ9"
    eu-central-1:
      version: "HvUVR_kpBdim8ljPC9lQGxlxE4ZvNiMg"
    eu-north-1:
      version: "V.OXo.ZUj9IzOdj18OiHDN0fx.YbBlkw"
    eu-west-1:
      version: "ZzC3vYuUYyiS1pHNiL.5ue1NJvVhynSn"
    eu-west-2:
      version: "KyuMFitdMb01O1OBDReGAMPCKEldrNBe"
    eu-west-3:
      version: "_2u89TNr4EtPsjcB4x2St5cp08s82OhZ"
    me-south-1:
      version: "sKUNDWickKZcP40s9BI_O9sWmEySsUPG"
    sa-east-1:
      version: "vdVmjfTODEjKKHou7lt7J908FQQEzzrW"
    us-east-1:
      version: "D8fQxcqOoSKERkZ.eW6EauluhoWF16Sm"
    us-east-2:
      version: ".3bkAChOZdlIcS5f0lQAwqa680hPHnml"
    us-gov-east-1:
      version: "JwkjmixsERNugXUwBlmUSa_e1n68mg6J"
    us-gov-west-1:
      version: "sKI4VctUnOohUVjnQ5KriaJkfKAslCq."
    us-west-1:
      version: "sF5ckTFyv2384Yye3XhJOlRyAZiM0TFm"
    us-west-2:
      version: "wwP8UyXoDaEjV7OEbfNQJ72ay.MjlLln"
Resources:
  CertbotToACMFunctionPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: Allow certbot-to-acm to access ACM.
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "acm:GetCertificate"
              - "acm:ImportCertificate"
              - "acm:ListCertificates"
              - "route53:ListHostedZones"
              - "route53:ListHostedZonesByName"
              - "route53:GetHostedZone"
              - "route53:GetChange"
              - "route53:ChangeResourceRecordSets"
              - "route53:ListResourceRecordSets"
              - "s3:GetObjectAcl"
              - "s3:PutObjectAcl"
              - "s3:ListBucket"
            Resource: "*"
  CertbotToACMFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSLambdaExecute"
        - !Ref CertbotToACMFunctionPolicy
  CertbotToACMFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Sub "ionosphere-public-${AWS::Region}"
        S3Key: "certbot-to-acm.zip"
        S3ObjectVersion: !FindInMap [CertbotToACMFunctionZIP, !Ref "AWS::Region", version]
      Description: Request a certificate from LetsEncrypt and store it in ACM.
      Handler: index.lambda_handler
      Layers:
        - !FindInMap [CertbotLayer, {"Ref": "AWS::Region"}, python38]
      MemorySize: 128
      Role: !GetAtt CertbotToACMFunctionRole.Arn
      Runtime: python3.8
      Timeout: 300
  CertbotToACMFunctionPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref CertbotToACMFunction
      Principal: events.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
Outputs:
  CertbotToACMFunctionName:
    Value: !Ref CertbotToACMFunction
